#!/bin/bash
set -e

cd $(dirname $0)/..

: ${CONFIG:=$(pwd)/config}
: ${DIST:=$(pwd)/dist}

./scripts/download

for arch in 'x86_64' 'aarch64'; do
  ./scripts/build-busybox ${CONFIG}/${arch}/buildroot-config ${CONFIG}/busybox-dynamic.config ${DIST}/${arch}
  ./scripts/package ${arch}
done
